sudo: required
services:
  - docker

before_install:
  - docker build -t abdoultodocker/docker-travis-ci-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true abdoultodocker/docker-travis-ci-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-887661588490"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_ACCESS_SECRET"

